import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import StoreProvider from "@/hook/redux/StoreProvider";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/hook/custom/AuhtProvider";
import { UserProvider } from "@/hook/custom/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} >
      <body className={inter.className + 'scroll-smooth'}>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <AuthProvider>
              <UserProvider>
                {children}
              </UserProvider>
            </AuthProvider>
            <ToastContainer />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
